name: tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  hardhat:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@v2
        uses: actions/checkout@v2

      - name: setup-node@v1
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install
        run: npm install

      - name: hardhat test
        env:
          MNEMONIC: ${{secrets.MNEMONIC}}
          KOVAN_RPC_URL: ${{secrets.KOVAN_RPC_URL}}
          ALCHEMY_MAINNET_RPC_URL: ${{secrets.ALCHEMY_MAINNET_RPC_URL}}
        run: npx hardhat test
